// Even fibonacci numbers

/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed n,
find the sum of the even-valued terms.
*/

// Solution
function fiboEvenSum(n) {
  let sum = 0;
  let a = 1;
  let b = 1;
  let c = 0;
  while (c < n) {
    c = a + b;
    a = b;
    b = c;
    if (c % 2 === 0) {
      sum += c;
    }
  }
  return sum;
}
